### ISSUE TITLE
Suggestion for second question in part 1

### ISSUE THREAD

**Issue by mandhri** [rusheni-123/Assignment-3#4]
Try this code
>meanofsamples<-rowMeans(x[,c(2:3)])
>meanofsamples
>x$meanofsamples<-rowMeans(x[,c(2:3)])
>x
>x[1:6,]

**Comment by rusheni-123** [comment]
Thanks for your suggestion Mandhri!
I used command 
x$meanofsamples <- rowMeans(x)
rowMeans(x[1:6,])
But when we used your suggested command,  presentation is clear.
So I used it for answering second question.
